// ============================================================
// TURN VIEW — one surface for one creature's turn
// ============================================================
// Running a turn took four windows: the Combat Tracker for whose turn it is,
// the bestiary for what the creature can do, the Attack Runner to roll it, and
// the battle map for where everyone is standing. This is those four collapsed
// into the span of one turn.
//
// It OWNS NOTHING. Every number on it lives somewhere else and is read through
// to its owner:
//
//   order, initiative, whose turn, HP, conditions → state.combatants, and the
//     Combat Tracker's own methods for anything that mutates the order
//   resource pools                                → state.party[i].resources
//   positions                                     → battlemap's own tokens
//   stat blocks and attacks                       → the same parse the Attack
//                                                    Runner uses
//   damage                                        → combat._applyHpDelta, so
//                                                    resistances, immunities
//                                                    and concentration all
//                                                    still apply
//
// That is the whole design constraint. A turn view holding its own copy of the
// initiative order would be a second tracker that silently disagrees with the
// first, and the disagreement would surface mid-fight.

registerPanel('turnview', {
  title: 'Turn View', icon: '⚔',

  _log: [],
  _pending: null,     // {kind:'hit'|'move', …} — an outcome awaiting a decision
  _armed: null,       // combatant id the next roll will hit
  _editInit: false,
  _mapBig: false,
  _artMode: 'auto',   // grid when compact, map art when enlarged
  _sig: null,
  _result: '',
  _resultLive: false,
  _drag: null,        // {id, from:{x,y}} while a token is being dragged

  mount(body){
    this._body = body;
    this._render();
    if (typeof on5eLoaded === 'function' && !(typeof _5eLoaded !== 'undefined' && _5eLoaded)){
      on5eLoaded(() => { if (this._body) this._render(); });
    }
    if (typeof load5eData === 'function') load5eData();
  },
  unmount(){ this._body = null; this._pending = null; },

  menuItems(){
    return [
      { label: '↻ Refresh from the tracker', run: () => this._render() },
      { label: '🧹 Clear this panel\'s log', run: () => { this._log = []; this._render(); } },
      { label: '🗺 Map art: ' + this._artMode, run: () => {
          this._artMode = this._artMode === 'auto' ? 'on' : this._artMode === 'on' ? 'off' : 'auto';
          this._render();
        } },
    ];
  },

  // ─── Sync ─────────────────────────────────────────────────────────────────
  // Called from save(), i.e. after any change anywhere. Same cheap-signature
  // trick the Attack Runner uses: build a string of only what this panel
  // displays and do nothing the vast majority of the time. Without it, ending
  // a turn in the Combat Tracker would leave this panel showing the previous
  // creature — the exact desync the "owns nothing" rule exists to prevent.
  _combatSig(){
    return String(state.activeCombatantId) + '#' + (state.combatRound || 0) + '#'
      + (state.combatants || []).map(c =>
          [c.id, c.name, c.hp, c.hpMax, c.ac, c.initiative, c.isPC ? 1 : 0,
           c.reactionUsed ? 1 : 0, (c.conditions || []).join(',')].join('~')
        ).join('|');
  },
  _syncFromCombat(){
    if (!this._body || this._applying) return;
    if (this._combatSig() === this._sig) return;
    this._render();
  },

  // ─── Reading the tracker ──────────────────────────────────────────────────
  _order(){ return state.combatants || []; },
  _active(){
    const o = this._order();
    return o.find(c => c.id === state.activeCombatantId) || o[0] || null;
  },
  _partyOf(c){
    return (c && c.isPC) ? (state.party || []).find(p => p.id === c.id) || null : null;
  },
  _entryOf(c){
    const C = panelDefs.combat;
    return (C && typeof C.statBlockFor === 'function') ? C.statBlockFor(c) : null;
  },

  _roll(dice){
    const m = String(dice || '').replace(/\s+/g, '').match(/^(\d*)d(\d+)([+-]\d+)?$/i);
    if (!m) return { total: 0, detail: '—' };
    const n = parseInt(m[1] || '1'), sides = parseInt(m[2]), mod = parseInt(m[3] || '0');
    const rolls = [];
    for (let i = 0; i < n; i++) rolls.push(1 + Math.floor(Math.random() * sides));
    const sum = rolls.reduce((a, b) => a + b, 0);
    return { total: Math.max(0, sum + mod), detail: rolls.join('+') + (mod ? (mod > 0 ? '+' + mod : String(mod)) : '') };
  },
  _d(n){ return 1 + Math.floor(Math.random() * n); },

  // ─── Reactions ────────────────────────────────────────────────────────────
  // The table is generated by tools/extract-reactions.js out of data/class,
  // data/feats.json and data/spells — 5 reactions come from base classes, 79
  // from subclasses, 17 from feats. Class and level alone would find 5 of 101,
  // which is why subclass is read too.
  //
  // The six below are the ones with real mechanics here. Everything else is
  // offered, spent and logged for the DM to adjudicate: automating a hundred
  // features badly would be worse than automating six honestly.
  MECH: {
    'Uncanny Dodge':    { when:'damage', halve:true },
    'Spirit Shield':    { when:'damage', reduce:[2,6], needs:'raging' },
    'Absorb Elements':  { when:'damage', halve:true,
                          onlyTypes:['acid','cold','fire','lightning','thunder'] },
    'Cutting Words':    { when:'tohit',  die:8 },
    'Defensive Duelist':{ when:'tohit',  pb:true },
    'Shield':           { when:'tohit',  ac:5 },
  },
  // What a reaction spends, named to match the party tracker's own pools. In
  // this panel those ARE the party tracker's pools — spending here decrements
  // state.party[i].resources[j] and the party card repaints, because there is
  // only one copy of the number.
  COST: {
    'Cutting Words':   { res:'Bardic Inspiration', n:1 },
    'Absorb Elements': { slot:1 },
    'Silvery Barbs':   { slot:1 },
    'Shield':          { slot:1 },
    'Spirit Shield':   { needs:'raging' },
  },

  _rxTable(){ return (typeof window !== 'undefined' && window.SKT_REACTIONS) || null; },

  // Proficiency bonus from level, for the handful of reactions that add it.
  _pb(lvl){ return 2 + Math.floor(Math.max(1, lvl || 1) - 1) / 4 | 0; },

  // Everything this creature could spend a reaction on, and where each came
  // from. A wrong guess by the derivation shows up as a visible chip rather
  // than silently shaping the prompt.
  _reactionsFor(c){
    const T = this._rxTable();
    if (!T) return [];
    const out = [];
    const p = this._partyOf(c);
    if (p){
      const sheet = p.sheet || {};
      const cls = String(p.cls || sheet.class || '').trim().toLowerCase();
      const sub = String(p.subclass || '').trim().toLowerCase();
      const lvl = parseInt(p.level || sheet.level || 0) || 0;
      T.classes.forEach(r => {
        if (r.cls.toLowerCase() === cls && r.lvl <= lvl) out.push({ ...r, from:'class' });
      });
      T.subclasses.forEach(r => {
        if (r.cls.toLowerCase() === cls && String(r.sub || '').toLowerCase() === sub && r.lvl <= lvl)
          out.push({ ...r, from:'subclass' });
      });
      // Feats aren't a structured field anywhere in the app — the closest thing
      // is the free-text "Features and Traits" box a PDF import fills. Matching
      // names against that text finds Defensive Duelist when it is written
      // down and finds nothing when it isn't, which is the honest answer.
      const featText = String(sheet.features || '') + ' ' + (Array.isArray(p.feats) ? p.feats.join(' ') : '');
      if (featText.trim()){
        const hay = featText.toLowerCase();
        T.feats.forEach(f => { if (hay.includes(f.name.toLowerCase())) out.push({ ...f, from:'feat' }); });
      }
      // Reaction spells can't come from class and level — they depend on what
      // this character actually has written down.
      const known = Array.isArray(sheet.spells) ? sheet.spells.map(s => String(s).toLowerCase()) : [];
      T.spells.forEach(sp => {
        if (known.includes(sp.name.toLowerCase())) out.push({ ...sp, from:'spell', scope:'self' });
      });
      out.forEach(r => { r._lvl = lvl; });
    } else {
      // A monster's reactions are printed in its stat block, so they are read
      // rather than derived — Parry, Snapping Bite, whatever the entry says.
      const raw = (this._entryOf(c) || {})._raw;
      this._rawList(raw, ['reactions', 'reaction']).forEach(r => {
        out.push({ name: r.name.replace(/\s*\(.*\)$/, ''), note: r.text, from:'stat block',
                   scope: this._scopeOf(r.text), range: this._rangeOf(r.text) });
      });
    }
    // Everyone has these, monsters included.
    (T.universal || []).forEach(r => out.push({ ...r, from:'always', scope:'self' }));

    const seen = new Set();
    return out.filter(r => !seen.has(r.name) && seen.add(r.name))
              .map(r => ({ ...r, key: r.name, ...(this.MECH[r.name] || {}) }));
  },

  // The loaded bestiary is the open5e-shaped normalisation, where a trait is
  // {name, desc} under `special_abilities` and a reaction is {name, desc} under
  // `reactions`. The 5etools shape — `trait`/`reaction` with `entries` — is
  // accepted too, so this doesn't break if the loader's normalisation changes.
  // Reading only one of the two was why the Ogre's stat block came out empty.
  _rawList(raw, names){
    if (!raw) return [];
    for (const n of names){
      const list = raw[n];
      if (Array.isArray(list) && list.length){
        return list.map(x => ({ name: String(x.name || ''),
                                text: x.desc != null ? String(x.desc) : this._flatten(x.entries) }));
      }
    }
    return [];
  },

  // A stat-block field as a readable line. The loader hands back strings for
  // some fields, arrays for the damage lists and an object for senses; an
  // empty array is the common case and must render as nothing, not as a label
  // with nothing after it.
  _plain(v){
    if (v == null) return '';
    if (Array.isArray(v)) return v.map(x => this._plain(x)).filter(Boolean).join(', ');
    if (typeof v === 'object'){
      return Object.keys(v).map(k => {
        const label = k.replace(/_/g, ' ').replace(/\b\w/g, m => m.toUpperCase());
        return label + ' ' + v[k];
      }).join(' · ');
    }
    return String(v).trim();
  },

  // 5etools markup → plain text, and the same trigger-scope reading the
  // extractor does, for the stat-block reactions it never sees.
  _flatten(entries){
    const parts = [];
    (function walk(n){
      if (Array.isArray(n)) n.forEach(walk);
      else if (n && typeof n === 'object'){ if (n.name) parts.push(n.name); Object.keys(n).forEach(k => { if (k !== 'name') walk(n[k]); }); }
      else if (typeof n === 'string') parts.push(n);
    })(entries);
    return parts.join(' ')
      .replace(/\{@(?:\w+)\s+([^}|]+)(?:\|[^}]*)?\}/g, '$1')
      .replace(/\s+/g, ' ').trim();
  },
  _rangeOf(txt){ const m = String(txt).match(/within (\d+) feet/i); return m ? parseInt(m[1], 10) : null; },
  _scopeOf(txt){
    const t = String(txt);
    const self = /hits you|against you|you are attacked|when you take damage|you suffer|reduced to 0 hit points/i.test(t);
    const allyIsAttacker = /another creature[^.]{0,30}(hits|attacks|makes an attack against) you/i.test(t);
    const ally = /another creature|you or a creature|an ally\b|other than you/i.test(t) && !allyIsAttacker;
    if (self && ally) return 'both';
    if (ally) return 'ally';
    if (self) return 'self';
    if (/makes an attack roll/i.test(t)) return 'both';
    return 'self';
  },

  // ─── Resource pools ───────────────────────────────────────────────────────
  _pool(c, name){
    const p = this._partyOf(c);
    return p && Array.isArray(p.resources) ? p.resources.find(r => r.name === name) || null : null;
  },
  _slot(c, min){
    const p = this._partyOf(c);
    if (!p) return null;
    for (let l = min; l <= 9; l++){
      const r = this._pool(c, 'Spell Slots L' + l);
      if (r && r.current > 0) return { kind:'res', res:r, lvl:l };
      const s = p.sheet && p.sheet.spellSlots && p.sheet.spellSlots[l];
      if (s && (s.total || 0) - (s.expended || 0) > 0) return { kind:'sheet', slot:s, lvl:l };
    }
    return null;
  },
  // null when payable. A cost this app doesn't track is NOT a blocker —
  // returning a problem for it would refuse a reaction the character really
  // has just because nobody has typed the pool in.
  _costProblem(c, r){
    const k = this.COST[r.name]; if (!k) return null;
    const p = this._partyOf(c);
    if (k.needs === 'raging' && p && !p.rage) return 'not raging';
    if (k.res){ const pool = this._pool(c, k.res); if (pool && pool.current < (k.n || 1)) return 'no ' + k.res.toLowerCase(); }
    if (k.slot && p && (this._hasAnySlotTracking(p)) && !this._slot(c, k.slot)) return 'no spell slot';
    return null;
  },
  _hasAnySlotTracking(p){
    if (Array.isArray(p.resources) && p.resources.some(r => /^Spell Slots L\d$/.test(r.name))) return true;
    return !!(p.sheet && p.sheet.spellSlots && Object.keys(p.sheet.spellSlots).length);
  },
  _costLabel(c, r){
    const k = this.COST[r.name]; if (!k) return '';
    if (k.res){ const pool = this._pool(c, k.res); return pool ? `${k.res} ${pool.current}/${pool.max}` : k.res + ' (untracked)'; }
    if (k.slot){ const s = this._slot(c, k.slot); return s ? 'slot L' + s.lvl : (this._partyOf(c) && this._hasAnySlotTracking(this._partyOf(c)) ? 'no slot' : 'slot (untracked)'); }
    if (k.needs) return k.needs;
    return '';
  },
  // Spends for real: this writes to state.party, which is the party tracker's
  // own array, then repaints that panel and saves.
  _payCost(c, r){
    const k = this.COST[r.name]; if (!k) return '';
    let spent = '';
    if (k.res){
      const pool = this._pool(c, k.res);
      if (pool){ pool.current = Math.max(0, pool.current - (k.n || 1)); spent = `${k.res} ${pool.current}/${pool.max}`; }
    }
    if (k.slot){
      const s = this._slot(c, k.slot);
      if (s && s.kind === 'res'){ s.res.current--; spent = `${s.res.name} ${s.res.current}/${s.res.max}`; }
      else if (s && s.kind === 'sheet'){ s.slot.expended = (s.slot.expended || 0) + 1; spent = `slot L${s.lvl} ${(s.slot.total||0)-s.slot.expended}/${s.slot.total||0}`; }
    }
    if (spent){ panelDefs.party?._render?.(); }
    return spent;
  },

  // ─── The map ──────────────────────────────────────────────────────────────
  // Battlemap's own tokens, matched the same way every other cross-panel link
  // in this app matches them: by name. Positions are stage pixels; one square
  // is _csScreen() of them.
  _bm(){ return panelDefs.battlemap || null; },
  // The battle map only reads its own saved state when it mounts, so a DM who
  // has never opened it this session would see an empty map here and — worse —
  // silently lose every reach test, since a creature with no token is treated
  // as distance-unknown. So: live panel when there is one, its saved state when
  // there isn't. The fallback is READ-ONLY on purpose. Writing tokens back into
  // skt-battlemap-v1 from here would mean reproducing battlemap's serializer,
  // and a partial write would destroy the fog and drawings stored beside them.
  _mapSrc(){
    const B = this._bm();
    if (B && Array.isArray(B._tokens) && B._tokens.length){
      let cs = B._cellSize || 50;
      try { if (B._csScreen) cs = B._csScreen() || cs; } catch(e){}
      return { live:true, tokens:B._tokens, cs, cols:B._cols || 24, rows:B._rows || 18 };
    }
    try {
      const d = JSON.parse(localStorage.getItem('skt-battlemap-v1') || 'null');
      if (d && Array.isArray(d.tokens)){
        return { live:false, tokens:d.tokens, cols:d.cols || 24, rows:d.rows || 18,
                 cs: (d.cellSize || 50) * (d.bgMapPath ? (d.bgMapScale || 1) : 1) };
      }
    } catch(e){}
    return { live:false, tokens:[], cs:50, cols:24, rows:18 };
  },
  _map(){ return this._mapCache || (this._mapCache = this._mapSrc()); },

  // Which slice of the battle map to show. Not the whole thing: a 24×18 map
  // with the fight happening in one corner renders as five dots in the top
  // left of a mostly-empty grid, which tells the DM nothing they can use. So
  // the thumbnail frames the creatures, padded, with a floor so two adjacent
  // tokens don't fill the box.
  //
  // The aspect ratio is forced to match the box because otherwise the cells
  // come out rectangular, and a grid whose squares aren't square is actively
  // misleading about distance — the one thing this map exists to show.
  _viewport(){
    if (this._drag && this._vp) return this._vp;      // don't pan under a drag
    const m = this._map(), cs = m.cs || 50;
    const RATIO = 1.45, PAD = 2, MINW = 10, MINH = 7;
    let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    m.tokens.forEach(t => {
      const x = Math.round(t.x / cs), y = Math.round(t.y / cs);
      x0 = Math.min(x0, x); y0 = Math.min(y0, y);
      x1 = Math.max(x1, x); y1 = Math.max(y1, y);
    });
    if (!isFinite(x0)) return (this._vp = { x:0, y:0, w:Math.min(MINW, m.cols), h:Math.min(MINH, m.rows) });
    x0 -= PAD; y0 -= PAD; x1 += PAD + 1; y1 += PAD + 1;   // +1: a token fills its own square
    let w = Math.max(MINW, x1 - x0), h = Math.max(MINH, y1 - y0);
    if (w / h < RATIO) w = Math.ceil(h * RATIO); else h = Math.ceil(w / RATIO);
    w = Math.min(w, m.cols); h = Math.min(h, m.rows);
    const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
    const x = Math.max(0, Math.min(Math.round(cx - w / 2), m.cols - w));
    const y = Math.max(0, Math.min(Math.round(cy - h / 2), m.rows - h));
    return (this._vp = { x, y, w, h });
  },
  _tokenFor(c){
    if (!c) return null;
    return this._map().tokens.find(t => t.label === c.name) || null;
  },
  _cs(){ return this._map().cs || 50; },
  // 5e counts a diagonal as 5 ft like any other square, so the metric is
  // Chebyshev. Euclidean would put a creature three squares away diagonally at
  // 21 ft instead of 15 and quietly change who can react.
  _feetBetween(a, b){
    const ta = this._tokenFor(a), tb = this._tokenFor(b);
    if (!ta || !tb) return null;                 // not on the map: unknown, not zero
    const cs = this._cs() || 50;
    const dx = Math.abs(ta.x - tb.x) / cs, dy = Math.abs(ta.y - tb.y) / cs;
    return Math.round(Math.max(dx, dy)) * 5;
  },
  _reachOf(c){
    if (c.isPC) return 5;
    const entry = this._entryOf(c);
    const raw = entry && entry._raw;
    // Read off the creature's own melee actions rather than assumed, so a
    // giant with a 10 ft reach provokes from 10 ft. Straight out of the action
    // text, which is where the number actually lives.
    let reach = 5;
    if (raw){
      const text = JSON.stringify(raw.actions || raw.action || '');
      const re = /reach (\d+) ?ft/gi;
      let m;
      while ((m = re.exec(text))) reach = Math.max(reach, parseInt(m[1], 10));
    }
    return reach;
  },
  _sideOf(c){ return c.isPC ? 'party' : 'foe'; },

  // ─── Who can react to this ────────────────────────────────────────────────
  _gatherReactions(o){
    const rows = [];
    this._order().forEach(c => {
      if (c.reactionUsed || (c.hp || 0) <= 0) return;
      if (o.attackerId && c.id === o.attackerId) return;    // not the one swinging
      const isTarget = c.id === o.target.id;
      this._reactionsFor(c).forEach(r => {
        // Only things with mechanics or an explicit hit trigger. Opportunity
        // Attack shouldn't appear every time someone is punched.
        if (!this.MECH[r.name] &&
            !/hits you|hit by an attack|takes damage|makes an attack roll|suffers a critical/i.test(r.note || '')) return;
        const ok = isTarget ? (r.scope === 'self' || r.scope === 'both')
                            : (r.scope === 'ally' || r.scope === 'both');
        if (!ok) return;
        if (r.when === 'damage' && !o.hit) return;          // nothing to reduce
        if (r.onlyTypes && !r.onlyTypes.includes(String(o.type || '').toLowerCase())) return;
        let ft = 0;
        if (!isTarget){
          ft = this._feetBetween(c, o.target);
          // Not on the map is not "out of range" — the DM may not be using it.
          if (ft != null && r.range != null && ft > r.range) return;
        }
        rows.push({ who:c, r, ft, problem: this._costProblem(c, r) });
      });
    });
    return rows;
  },

  // ─── Render ───────────────────────────────────────────────────────────────
  _render(){
    const b = this._body; if (!b) return;
    this._sig = this._combatSig();
    // Re-read the map once per render rather than once per distance test:
    // _gatherReactions asks for the distance between every pair of creatures.
    this._mapCache = null; this._map();
    const order = this._order();

    if (!order.length){
      b.innerHTML = `<div class="tv-root tv-root-empty">` + emptyState({
        icon:'i-combat',
        title:'No one is in the fight yet',
        hint:'Add combatants in the <strong>Combat Tracker</strong> — this panel runs whatever is in there, it doesn\'t keep its own list.',
      }) + `</div>`;
      return;
    }
    const c = this._active();

    b.innerHTML = `<div class="tv-root">
      <div class="tv-initbar">
        <div class="tv-init">${this._renderInit()}</div>
        <div class="tv-init-tools">${this._renderInitTools()}</div>
      </div>
      ${this._editInit ? this._renderAddRow() : ''}
      <div class="tv-main">
        <div class="tv-actor">
          ${this._renderActorHead(c)}
          ${this._renderActions(c)}
          <div class="tv-result${this._resultLive ? ' on' : ''}" role="status" aria-live="polite">${this._result
            || '<span class="dim">Pick a target, then roll an attack.</span>'}</div>
          <div class="tv-tail">
            <div class="tv-traits">${this._renderTraits(c)}</div>
            <div class="tv-log">${this._renderLog()}</div>
          </div>
        </div>
        <div class="tv-side">
          ${this._renderMap()}
          <div class="tv-targets">${this._renderTargets(c)}</div>
          <div class="tv-adjust">${this._renderAdjust()}</div>
        </div>
      </div>
      ${this._renderPending()}
      <div class="tv-foot">
        <div class="tv-turnline">${this._renderTurnline(c)}</div>
        <button class="btn primary tv-end" data-tv="end">End turn</button>
      </div>
    </div>`;
    this._wire();
    this._placeTokens();
  },

  _renderInit(){
    const order = this._order();
    const activeId = state.activeCombatantId;
    if (this._editInit){
      return order.map(c => `
        <span class="tv-pip edit ${c.id === activeId ? 'cur' : ''}">
          <input class="tv-init-in" type="number" data-tvinit="${esc(c.id)}" value="${c.initiative ?? 0}"
                 aria-label="${esc(c.name)} initiative">
          <span><span class="tv-pip-name">${esc(c.name)}</span><br>
          <span class="tv-pip-hp">${(c.initBonus || 0) >= 0 ? '+' : ''}${c.initBonus || 0} init</span></span>
          <button class="tv-pip-x" data-tv="rm" data-id="${esc(c.id)}"
                  title="Remove ${esc(c.name)} from the fight" aria-label="Remove ${esc(c.name)}">&times;</button>
        </span>`).join('');
    }
    let seenActive = false;
    return order.map(c => {
      const cur = c.id === activeId;
      if (cur) seenActive = true;
      const dead = (c.hp || 0) <= 0;
      return `<button class="tv-pip ${cur ? 'cur' : ''} ${!cur && !seenActive ? 'done' : ''} ${dead ? 'dead' : ''}"
                      data-tv="jump" data-id="${esc(c.id)}" aria-current="${cur}">
        <span class="tv-pip-init">${c.initiative ?? '–'}</span>
        <span><span class="tv-pip-name">${esc(c.name)}</span><br>
        <span class="tv-pip-hp">${c.hp}/${c.hpMax}</span></span>
      </button>`;
    }).join('');
  },
  _renderInitTools(){
    return this._editInit
      ? `<button class="btn" data-tv="rollinit" title="Roll initiative for the monsters — players call their own out loud">Roll NPCs</button>
         <button class="btn primary" data-tv="initdone">Done</button>`
      : `<span class="tv-round">Round ${state.combatRound || 1}</span>
         <button class="btn" data-tv="initedit" title="Set initiative, add or remove combatants">Initiative</button>`;
  },
  _renderAddRow(){
    return `<div class="tv-init-add">
      <span class="tv-manual-l">Add</span>
      <input class="tv-in wide" data-tvadd="name" placeholder="name" aria-label="Name">
      <input class="tv-in" data-tvadd="init" type="number" placeholder="init" aria-label="Initiative">
      <input class="tv-in" data-tvadd="hp" type="number" placeholder="hp" aria-label="Hit points">
      <input class="tv-in" data-tvadd="ac" type="number" placeholder="ac" aria-label="Armour class">
      <button class="btn primary" data-tv="add">Add</button>
      <span class="tv-note">Blank initiative rolls a d20. For a creature with a stat block, add it
        from the Bestiary or the Combat Tracker so its attacks come with it.</span>
    </div>`;
  },

  _renderActorHead(c){
    const p = this._partyOf(c);
    const entry = this._entryOf(c);
    const sub = p ? [p.cls, p.subclass, p.level ? 'level ' + p.level : ''].filter(Boolean).join(' · ')
                  : (entry && entry.meta) || (c.isPC ? 'Player character' : 'No stat block');
    const conds = (c.conditions || []).map(x => `<span class="tv-cond">${esc(x)}</span>`).join('');
    const res = p && Array.isArray(p.resources) ? p.resources.map(r => {
      const max = Math.max(0, Math.min(20, r.max || 0));
      let pips = '';
      for (let i = 0; i < max; i++) pips += `<span class="tv-pip-o ${i < r.current ? '' : 'off'}"></span>`;
      return `<span class="tv-res-i">${esc(r.name)}<span class="tv-pips">${pips}</span></span>`;
    }).join('') : '';
    const rx = this._reactionsFor(c);
    const rxHtml = !rx.length ? '' :
      `<span class="tv-rx-l">Reactions</span>` + rx.map(r =>
        `<span class="tv-rx ${c.reactionUsed ? 'spent' : ''} ${this.MECH[r.name] ? 'hit' : ''}"
               title="${esc(r.note || '')}">${esc(r.name)}<span class="tv-rx-src">${esc(r.from)}${r.lvl ? ' L' + r.lvl : ''}${
          r.scope === 'ally' ? ' · ally' : r.scope === 'both' ? ' · either' : ''}</span></span>`).join('');
    return `<div class="tv-actor-head">
        <div class="tv-avatar">${esc(String(c.name || '?').trim().charAt(0).toUpperCase())}</div>
        <div class="tv-actor-id">
          <div class="tv-actor-name">${esc(c.name)}</div>
          <div class="tv-actor-sub">${esc(sub)}</div>
        </div>
        <div class="tv-vitals">
          <div class="tv-vital"><div class="l">HP</div><div class="v">${c.hp}</div></div>
          <div class="tv-vital"><div class="l">AC</div><div class="v">${c.ac ?? '–'}</div></div>
        </div>
      </div>
      ${conds ? `<div class="tv-conds">${conds}</div>` : ''}
      ${rxHtml ? `<div class="tv-rxlist">${rxHtml}</div>` : ''}
      ${res ? `<div class="tv-res">${res}</div>` : ''}`;
  },

  // A creature's attacks: the parsed stat block for a monster, the imported
  // sheet's weapon rows for a PC. Neither is invented here — both come from
  // the same places the rest of the app reads them.
  _attacksFor(c){
    if (c.isPC){
      const p = this._partyOf(c);
      const rows = (p && p.sheet && Array.isArray(p.sheet.attacks)) ? p.sheet.attacks : [];
      return rows.filter(a => a && a.name).map(a => ({
        name: a.name, pc: true,
        bonus: parseInt(String(a.atkBonus || '').replace(/[^\d+-]/g, ''), 10) || 0,
        dmgText: a.damage || '',
      }));
    }
    const entry = this._entryOf(c);
    const raw = entry && entry._raw;
    if (!raw || !panelDefs.attacks) return [];
    return panelDefs.attacks._parsed(raw).attacks || [];
  },

  _renderActions(c){
    const list = this._attacksFor(c);
    const manual = `<div class="tv-manual ${list.length ? '' : 'lead'}">
      <span class="tv-manual-l">${list.length ? 'Rolled it yourself?' : esc(c.name) + ' rolls — enter the result:'}</span>
      <input class="tv-in" data-tvman="tohit" type="number" placeholder="hit" aria-label="Attack roll total">
      <input class="tv-in" data-tvman="dmg" type="number" placeholder="dmg" aria-label="Damage">
      <input class="tv-in wide" data-tvman="type" type="text" placeholder="type" aria-label="Damage type">
      <button class="btn ${list.length ? '' : 'primary'}" data-tv="manual">Apply</button>
    </div>`;
    if (!list.length){
      return `<div class="tv-actions">${manual}
        <div class="tv-act-line" style="padding:0 2px">Or use the −/+ under the target list for damage
        and healing that isn't an attack.</div></div>`;
    }
    const rows = list.map((a, i) => {
      const line = a.pc
        ? `${a.bonus >= 0 ? '+' : ''}${a.bonus} to hit · ${esc(a.dmgText || '—')}`
        : `${esc(a.toHit || '')}${a.toHit ? ' to hit · ' : ''}${(a.parts || []).map(pt => `${pt.avg} (${esc(pt.dice)}) ${esc(pt.type)}`).join(' + ')}`;
      const rollable = a.pc ? !!a.dmgText : !a.save && (a.parts || []).length;
      return `<div class="tv-act">
        <div class="tv-act-body">
          <div class="tv-act-name">${esc(a.name)}</div>
          <div class="tv-act-line">${line}</div>
        </div>
        ${rollable ? `<button class="btn" data-tv="roll" data-ai="${i}" aria-label="Roll ${esc(a.name)}">${ICO('i-dice')}Roll</button>`
                   : `<span class="tv-act-note">${a.save ? 'save — use the Attack Runner' : 'no damage parsed'}</span>`}
      </div>`;
    }).join('');
    return `<div class="tv-actions">${rows}${manual}</div>`;
  },

  // The rest of the stat block — the part a two-action monster otherwise
  // leaves as a hole under its actions.
  _renderTraits(c){
    const p = this._partyOf(c);
    const bits = [], traits = [];
    if (p){
      if (p.spd) bits.push('Speed ' + p.spd + ' ft');
      if (p.pp) bits.push('Passive Perception ' + p.pp);
      if (p.rage) bits.push('Raging');
      if (p.concentration) bits.push('Concentrating on ' + p.concentration);
      (p.buffs || []).forEach(b => traits.push({ name: b.label || 'Buff', text: b.note || '' }));
    } else {
      const entry = this._entryOf(c);
      if (entry){
        const raw = entry._raw || {};
        if (entry.speed || raw.speed) bits.push('Speed ' + this._plain(entry.speed || raw.speed));
        // senses is an OBJECT here ({darkvision:'60 ft.', passive_perception:8})
        // and the damage lists are arrays, empty far more often than not.
        // String()-ing either gave "[object Object]" and a bare "Resists".
        const sen = this._plain(raw.senses); if (sen) bits.push(sen);
        const lang = this._plain(raw.languages); if (lang) bits.push(lang);
        const res = this._plain(raw.damage_resistances); if (res) bits.push('Resists ' + res);
        const imm = this._plain(raw.damage_immunities); if (imm) bits.push('Immune ' + imm);
        const cim = this._plain(raw.condition_immunities); if (cim) bits.push('Immune to ' + cim);
        this._rawList(raw, ['special_abilities', 'trait']).forEach(t => traits.push(t));
      }
    }
    (c.buffs || []).forEach(b => { if (!traits.some(t => t.name === (b.label || 'Buff'))) traits.push({ name: b.label || 'Buff', text: b.note || '' }); });
    const p1 = bits.length ? `<div class="tv-passive">${bits.map(x => `<span>${esc(x)}</span>`).join('')}</div>` : '';
    const p2 = traits.length ? `<div class="tv-traits-l">Traits</div>` + traits.map(t =>
      `<div class="tv-trait"><b>${esc(t.name)}</b>${t.text ? ' — ' + esc(t.text) : ''}</div>`).join('') : '';
    // A PC's class features are the Party panel's Features tab, which resolves
    // them from the same class data. Pointed at rather than reimplemented —
    // two renderers for one list is two things to keep in step.
    const p3 = p ? `<div class="tv-trait" style="color:var(--text-dim)">Class and subclass features
      are in the Party panel's <b>Features</b> tab.</div>` : '';
    return p1 + p2 + p3;
  },

  _renderTargets(c){
    const rows = this._order().filter(t => t.id !== (c && c.id)).map(t => {
      const pct = t.hpMax ? Math.max(0, (t.hp / t.hpMax) * 100) : 0;
      const col = pct <= 0 ? '#5a3a3a' : pct < 35 ? 'var(--danger)' : pct < 75 ? 'var(--warning)' : 'var(--success)';
      // A creature holding an unspent reaction that could ANSWER an attack is
      // worth seeing before you commit, not only once the prompt appears.
      // Everyone has Opportunity Attack, so flagging that would mark the table.
      const r = (!t.reactionUsed && this._reactionsFor(t).some(x => this.MECH[x.name]))
        ? '<span class="tv-pip-r" title="Has an unspent reaction that can answer an attack">R</span>' : '';
      return `<button class="tv-tgt ${this._armed === t.id ? 'armed' : ''}" data-tv="arm" data-id="${esc(t.id)}"
                      aria-pressed="${this._armed === t.id}">
        <span class="tv-tgt-row">
          <span class="tv-tgt-name">${esc(t.name)}${r}</span>
          <span class="tv-tgt-hp">${t.hp}/${t.hpMax}</span>
          <span class="tv-tgt-ac">${ICO('i-shield')}${t.ac ?? '–'}</span>
        </span>
        <span class="tv-hpbar"><i style="width:${pct}%;background:${col}"></i></span>
      </button>`;
    }).join('');
    return '<h4>Target</h4>' + (rows || '<div class="tv-act-line">No one else in the fight.</div>');
  },
  _renderAdjust(){
    const a = this._order().find(x => x.id === this._armed);
    return `<span class="tv-adjust-name">${a ? esc(a.name) : 'Pick a target'}</span>
      <button class="btn" data-tv="adj" data-sign="-1" ${a ? '' : 'disabled'} aria-label="Damage">−</button>
      <input class="tv-in" data-tvadj="amt" type="number" value="5" style="width:46px" aria-label="Amount">
      <button class="btn" data-tv="adj" data-sign="1" ${a ? '' : 'disabled'} aria-label="Heal">+</button>`;
  },

  _renderTurnline(c){
    const o = this._order();
    const i = o.findIndex(x => x.id === (c && c.id));
    const n = o[(i + 1) % o.length];
    return `<b>${esc(c ? c.name : '—')}</b>'s turn · next up <b>${esc(n ? n.name : '—')}</b>`;
  },
  _renderLog(){
    return this._log.length
      ? this._log.slice(0, 8).map(l => `<div class="tv-log-line">${l}</div>`).join('')
      : '<div class="tv-log-line" style="opacity:.55">Rolls this combat appear here.</div>';
  },

  _renderMap(){
    const onMap = this._order().filter(c => this._tokenFor(c)).length;
    // The grid is sized in _placeTokens, once the box has real pixels.
    return `<div class="tv-map${this._mapBig ? ' big' : ''}">
      <div class="tv-map-grid"></div>
      <div class="tv-map-hint">${esc(this._mapHint(onMap))}</div>
    </div>`;
  },
  _mapHint(onMap){
    if (!onMap) return 'no tokens on the battle map';
    if (!this._map().live) return 'open the Battle Map to move tokens';
    if (this._mapBig) return 'drag a token — reach updates live, and leaving it provokes';
    // "hover" is a lie on a phone, where pointerenter fires from a tap.
    return matchMedia('(pointer: coarse)').matches ? 'tap to enlarge' : 'hover to enlarge';
  },
  // Tokens are absolutely positioned from the real ones' stage coordinates, so
  // the thumbnail is a view of battlemap's data rather than a second copy.
  _placeTokens(){
    const b = this._body; if (!b) return;
    const m = b.querySelector('.tv-map'); if (!m) return;
    m.querySelectorAll('.tv-tok').forEach(n => n.remove());
    const src = this._map(), vp = this._viewport();
    const cs = src.cs || 50;
    const W = m.clientWidth || 250, H = m.clientHeight || 172;
    // ONE cell size for both axes, letterboxed. Fitting the viewport to the box
    // independently per axis would give rectangular cells, and a grid whose
    // squares aren't square misreports the one thing this map exists to show.
    const cell = Math.min(W / vp.w, H / vp.h);
    const offX = (W - cell * vp.w) / 2, offY = (H - cell * vp.h) / 2;
    const g = m.querySelector('.tv-map-grid');
    if (g){
      g.style.left = offX + 'px'; g.style.top = offY + 'px';
      g.style.width = (cell * vp.w) + 'px'; g.style.height = (cell * vp.h) + 'px';
      g.style.right = 'auto'; g.style.bottom = 'auto';
      g.style.backgroundSize = cell + 'px ' + cell + 'px';
    }
    m.style.setProperty('--tok', Math.max(12, cell * 0.9) + 'px');
    const frag = document.createDocumentFragment();
    this._order().forEach(c => {
      const t = this._tokenFor(c); if (!t) return;
      const n = document.createElement('div');
      n.className = 'tv-tok ' + (c.isPC ? 'pc ' : '')
        + (c.id === state.activeCombatantId ? 'cur ' : '') + (this._armed === c.id ? 'tgt ' : '')
        + ((c.hp || 0) <= 0 ? 'dead' : '');
      n.dataset.tvtok = c.id;
      n.title = c.name + ' — ' + c.hp + '/' + c.hpMax;
      n.textContent = String(c.name || '?').trim().charAt(0).toUpperCase();
      n.style.left = (offX + ((t.x / cs) - vp.x + 0.5) * cell) + 'px';
      n.style.top  = (offY + ((t.y / cs) - vp.y + 0.5) * cell) + 'px';
      frag.appendChild(n);
    });
    m.appendChild(frag);
  },

  _renderPending(){
    const o = this._pending;
    if (!o) return '<div class="tv-react" hidden></div>';
    if (o.kind === 'move'){
      const opts = o.rows.map(w => `<button class="btn" data-tv="oa" data-id="${esc(w.id)}"
          title="${esc(w.name)} had ${esc(o.mover.name)} within ${this._reachOf(w)} ft">
          <span class="tv-react-who">${esc(w.name)}</span>Opportunity Attack</button>`).join('');
      return `<div class="tv-react"><span class="tv-react-l">Opportunity attack?</span>
        <span class="tv-react-note">${esc(o.mover.name)} moved ${o.moved} ft, out of reach</span>
        ${opts}<button class="btn primary" data-tv="oa" data-id="">No reaction</button></div>`;
    }
    const rows = this._gatherReactions(o);
    const opts = rows.map(({ who, r, ft, problem }) => {
      let preview = '';
      if (r.when === 'damage' && r.halve) preview = ` → ${Math.floor(o.dmg / 2)}`;
      if (r.when === 'damage' && r.reduce) preview = ` −${r.reduce[0]}d${r.reduce[1]}`;
      if (r.when === 'tohit' && r.ac) preview = ` AC +${r.ac}`;
      const mine = who.id === o.target.id;
      const cost = this._costLabel(who, r);
      const far = mine || ft == null ? '' : ` ${ft} ft`;
      return `<button class="btn ${problem ? 'tv-cant' : ''}" data-tv="react" data-who="${esc(who.id)}"
                      data-key="${esc(r.key)}" ${problem ? 'disabled' : ''} title="${esc(r.note || '')}">
        ${mine ? '' : `<span class="tv-react-who">${esc(who.name)}</span>`}${esc(r.name)}${preview}
        <span class="tv-react-cost">${problem ? '· ' + esc(problem) : (cost ? '· ' + esc(cost) : '')}${esc(far)}</span>
      </button>`;
    }).join('');
    return `<div class="tv-react"><span class="tv-react-l">Reaction?</span>
      <span class="tv-react-note">${esc(o.target.name)} ${o.hit ? `takes ${o.dmg} ${esc(o.type || 'damage')}` : 'was missed'}
        — ${o.total} vs AC ${(o.target.ac || 0) + (o.acBonus || 0)}</span>
      ${opts}
      <button class="btn primary" data-tv="react" data-who="" data-key="__none">${o.hit ? `Take ${o.dmg}` : 'Let it miss'}</button>
    </div>`;
  },

  _setResult(html, live){ this._result = html; this._resultLive = !!live; },

  // ─── Resolving an attack ──────────────────────────────────────────────────
  // A hit is held un-committed only when someone actually has an unused
  // reaction that could change it, so the common case stays two clicks.
  _resolve(o){
    o.kind = 'hit';
    if (o.hit && this._gatherReactions(o).length){ this._pending = o; this._render(); return; }
    this._commit(o, null);
  },
  _commit(o, usedName){
    const t = o.target;
    const tag = usedName ? ` <span class="dim">(${esc(usedName)})</span>` : '';
    this._pending = null;
    if (!o.hit){
      this._setResult(`<span class="miss">Miss</span> — ${esc(o.label)} vs ${esc(t.name)}:
        <strong>${o.total}</strong> <span class="dim">vs AC ${t.ac}</span>${tag}`, true);
      this._log.unshift(`<strong>${esc(o.attacker)}</strong> missed <strong>${esc(t.name)}</strong> with ${esc(o.label)}${usedName ? ' — ' + esc(usedName) : ''}`);
      save(); this._render(); return;
    }
    const before = t.hp;
    this._applyDamage(t, o.dmg, o.type, o.magical);
    const after = (this._order().find(x => x.id === t.id) || t).hp;
    const breakdown = o.detail ? ` <span class="dim">[${esc(o.detail)}]</span>` : '';
    this._setResult(`<span class="${o.crit ? 'crit' : 'hit'}">${o.crit ? 'Critical hit' : 'Hit'}</span> —
      ${esc(o.label)} vs ${esc(t.name)}: <strong>${o.total}</strong> <span class="dim">vs AC ${t.ac}</span> ·
      <strong>${o.dmg} ${esc(o.type || 'damage')}</strong>${breakdown}${tag}
      <span class="dim">· ${esc(t.name)} ${before} → ${after}</span>`, true);
    this._log.unshift(`<strong>${esc(o.attacker)}</strong> hit <strong>${esc(t.name)}</strong> for <strong>${o.dmg}</strong> ${esc(o.type || '')}${o.crit ? ' (crit)' : ''}${usedName ? ' — ' + esc(usedName) : ''} <span style="opacity:.7">· ${before} → ${after}</span>`);
    this._render();
  },
  // Straight through the Combat Tracker, so resistances, immunities,
  // concentration checks, death saves and the party write-back all happen
  // exactly as they do when the damage is typed in there by hand.
  _applyDamage(target, amount, type, magical){
    const C = panelDefs.combat; if (!C) return;
    const i = this._order().indexOf(target);
    if (i < 0 || !amount) return;
    const prev = C._lastAtkProp;
    C._lastAtkProp = magical ? 'magical' : null;
    this._applying = true;
    try { C._applyHpDelta(i, -amount, type || null); }
    finally { C._lastAtkProp = prev; this._applying = false; }
    C._render?.();
  },

  _useReaction(whoId, key){
    const o = this._pending; if (!o || o.kind !== 'hit') return;
    const who = this._order().find(c => c.id === whoId);
    const r = who && this._reactionsFor(who).find(x => x.key === key);
    if (!r) return;
    const problem = this._costProblem(who, r);
    if (problem){ this._setResult(`<span class="dim">${esc(who.name)} can't — ${esc(problem)}.</span>`, true); this._render(); return; }
    who.reactionUsed = true;
    const spent = this._payCost(who, r);
    const by = (who.id === o.target.id ? r.name : `${who.name}'s ${r.name}`) + (spent ? ` · ${spent}` : '');

    if (r.when === 'damage'){
      const was = o.dmg;
      if (r.halve) o.dmg = Math.floor(o.dmg / 2);
      else if (r.reduce){ let n = 0; for (let i = 0; i < r.reduce[0]; i++) n += this._d(r.reduce[1]); o.dmg = Math.max(0, o.dmg - n); }
      this._commit(o, `${by}, ${was} → ${o.dmg}`);
      return;
    }
    if (r.when === 'tohit'){
      // A to-hit reaction can turn a hit into a miss, so the roll is re-tested
      // against AC rather than assumed still to land.
      let desc;
      if (r.ac != null){ o.acBonus = (o.acBonus || 0) + r.ac; desc = `${by}, AC +${r.ac}`; }
      else {
        const sub = r.pb ? this._pb(r._lvl || (this._partyOf(who) || {}).level) : this._d(r.die);
        o.total -= sub; desc = `${by}, −${sub}`;
      }
      o.hit = o.crit || o.total >= ((o.target.ac || 0) + (o.acBonus || 0));
      this._commit(o, desc);
      return;
    }
    this._commit(o, by);   // no mechanics: spent, logged, the DM adjudicates
  },

  _rollAttack(ai){
    const c = this._active();
    const t = this._order().find(x => x.id === this._armed);
    if (!t){ this._setResult('<span class="dim">Pick a target on the right first.</span>'); this._render(); return; }
    const a = this._attacksFor(c)[ai]; if (!a) return;
    const nat = this._d(20);
    const bonus = a.pc ? a.bonus : (parseInt(String(a.toHit || '').replace(/[^\d+-]/g, ''), 10) || 0);
    const total = nat + bonus;
    const crit = nat === 20;
    const hit = crit || (nat !== 1 && total >= (t.ac || 10));
    let dmg = 0, type = '', detail = '';
    if (a.pc){
      // "1d8+3 slashing" off the imported sheet.
      const m = String(a.dmgText).match(/(\d*d\d+(?:\s*[+-]\s*\d+)?)\s*(.*)/i);
      const r = this._roll(m ? m[1] : a.dmgText);
      const r2 = crit ? this._roll((m ? m[1] : '').replace(/^(\d*)d/, (s, n) => (2 * (parseInt(n || '1'))) + 'd')) : null;
      dmg = (r2 || r).total; detail = (r2 || r).detail;
      type = (m && m[2] ? m[2] : '').trim().replace(/^damage\s*/i, '');
    } else {
      // Every damage part is rolled and applied on its own type, the same rule
      // the Attack Runner follows — a dragon's bite is piercing PLUS fire, and
      // a target resistant to fire must halve only the fire half.
      const parts = (a.parts || []).map(pt => {
        const dice = crit ? String(pt.dice).replace(/^(\d*)d/, (s, n) => (2 * (parseInt(n || '1'))) + 'd') : pt.dice;
        const r = this._roll(dice);
        return { amt: r.total, type: pt.type, detail: pt.type + ' ' + r.detail };
      });
      dmg = parts.reduce((s, x) => s + x.amt, 0);
      type = parts.length ? parts[0].type : '';
      detail = parts.map(x => x.detail).join(' · ');
      if (parts.length > 1) this._multi = parts;
    }
    this._resolve({ attackerId: c.id, attacker: c.name, label: a.name, target: t,
                    total, crit, hit, dmg, type, detail,
                    magical: !a.pc && panelDefs.attacks && this._entryOf(c) && this._entryOf(c)._raw
                             ? panelDefs.attacks._parsed(this._entryOf(c)._raw).magical : false });
  },

  _manualAttack(){
    const b = this._body;
    const t = this._order().find(x => x.id === this._armed);
    if (!t){ this._setResult('<span class="dim">Pick a target on the right first.</span>'); this._render(); return; }
    const total = parseInt(b.querySelector('[data-tvman="tohit"]').value, 10);
    const dmg = parseInt(b.querySelector('[data-tvman="dmg"]').value, 10);
    if (isNaN(total) || isNaN(dmg)){
      this._setResult('<span class="dim">Enter both the attack total and the damage.</span>'); this._render(); return;
    }
    const type = (b.querySelector('[data-tvman="type"]').value || '').trim();
    const c = this._active();
    this._resolve({ attackerId: c && c.id, attacker: c ? c.name : 'Someone', label: 'attack', target: t,
                    total, crit: false, hit: total >= (t.ac || 10), dmg, type, detail: '' });
  },

  _adjust(sign){
    const t = this._order().find(x => x.id === this._armed); if (!t) return;
    const el = this._body.querySelector('[data-tvadj="amt"]');
    const n = Math.abs(parseInt(el && el.value, 10) || 0); if (!n) return;
    const before = t.hp;
    const C = panelDefs.combat; if (!C) return;
    const i = this._order().indexOf(t);
    this._applying = true;
    try { C._applyHpDelta(i, sign < 0 ? -n : n, null); } finally { this._applying = false; }
    C._render?.();
    const after = (this._order().find(x => x.id === t.id) || t).hp;
    const word = sign < 0 ? 'took' : 'regained';
    this._setResult(`<span class="dim">${esc(t.name)} ${word} <strong>${n}</strong> — ${before} → ${after}</span>`, true);
    this._log.unshift(`<strong>${esc(t.name)}</strong> ${word} <strong>${n}</strong> <span style="opacity:.7">· ${before} → ${after}</span>`);
    this._render();
  },

  // ─── Opportunity attacks ──────────────────────────────────────────────────
  // The one reaction triggered by movement rather than by a roll, which is why
  // the hit prompt could never house it. Its home is the map.
  _provokedBy(mover, fromXY){
    const cs = this._cs() || 50;
    const at = { x: fromXY.x, y: fromXY.y };
    const ft = (t, q) => Math.round(Math.max(Math.abs(t.x - q.x), Math.abs(t.y - q.y)) / cs) * 5;
    const now = this._tokenFor(mover);
    if (!now) return [];
    return this._order().filter(c => {
      if (c.id === mover.id || (c.hp || 0) <= 0 || c.reactionUsed) return false;
      if (this._sideOf(c) === this._sideOf(mover)) return false;
      const t = this._tokenFor(c); if (!t) return false;
      const reach = this._reachOf(c);
      return ft(t, at) <= reach && ft(t, now) > reach;   // had them, doesn't now
    });
  },
  _useOA(whoId){
    const o = this._pending; if (!o || o.kind !== 'move') return;
    const who = this._order().find(c => c.id === whoId);
    this._pending = null;
    if (!who){ this._render(); return; }
    who.reactionUsed = true;
    const melee = this._attacksFor(who).find(a => !a.save && (a.pc ? a.dmgText : (a.parts || []).length));
    if (melee){
      const prevArmed = this._armed, prevActive = state.activeCombatantId;
      // Roll it as that creature's attack against the mover, then put the turn
      // pointer back — an opportunity attack does not take anyone's turn.
      state.activeCombatantId = who.id;
      this._armed = o.mover.id;
      const idx = this._attacksFor(who).indexOf(melee);
      this._rollAttack(idx);
      state.activeCombatantId = prevActive;
      if (!this._pending) this._armed = prevArmed;
      return;
    }
    this._setResult(`<strong>${esc(who.name)}</strong> takes an opportunity attack on
      <strong>${esc(o.mover.name)}</strong> <span class="dim">— roll it, then use the manual row
      or the −/+ under the target list.</span>`, true);
    this._log.unshift(`<strong>${esc(who.name)}</strong> opportunity attack on <strong>${esc(o.mover.name)}</strong> <span style="opacity:.7">· reaction spent</span>`);
    save(); this._render();
  },

  // ─── Initiative, add and remove ───────────────────────────────────────────
  // All four delegate to the Combat Tracker rather than reimplementing it. Its
  // _removeCombatantAt already handles passing the turn on and ticking the
  // round when the last creature in the order leaves; a second implementation
  // here would be a second set of those bugs.
  _setInit(id, v){
    const c = this._order().find(x => x.id === id);
    if (!c || isNaN(v)) return;
    c.initiative = v;
    panelDefs.combat?._sortByInitiative?.(true);
    save(); panelDefs.combat?._render?.(); this._render();
  },
  _rollNpcInit(){
    this._order().forEach(c => {
      if (c.isPC) return;
      c.initiative = this._d(20) + (c.initBonus || 0);
    });
    panelDefs.combat?._sortByInitiative?.(true);
    this._setResult('<span class="dim">Rolled initiative for '
      + this._order().filter(c => !c.isPC).map(c => esc(c.name) + ' ' + c.initiative).join(', ') + '.</span>', true);
    save(); panelDefs.combat?._render?.(); this._render();
  },
  _addCombatant(){
    const b = this._body;
    const g = k => b.querySelector(`[data-tvadd="${k}"]`);
    const name = (g('name').value || '').trim();
    if (!name){ this._setResult('<span class="dim">Give the combatant a name.</span>'); this._render(); return; }
    const iv = parseInt(g('init').value, 10);
    const hp = Math.max(1, parseInt(g('hp').value, 10) || 10);
    const ac = Math.max(1, parseInt(g('ac').value, 10) || 10);
    state.combatants.push({ id: uid(), name, isPC: false, hp, hpMax: hp, ac,
                            initBonus: 0, initiative: isNaN(iv) ? this._d(20) : iv, conditions: [] });
    if (!state.combatRound) state.combatRound = 1;
    panelDefs.combat?._sortByInitiative?.(true);
    ['name','init','hp','ac'].forEach(k => { g(k).value = ''; });
    this._log.unshift(`<strong>${esc(name)}</strong> joined the fight`);
    this._setResult(`<span class="dim"><strong>${esc(name)}</strong> added, ${hp} HP.</span>`, true);
    save(); panelDefs.combat?._render?.(); this._render();
    this._body.querySelector('[data-tvadd="name"]')?.focus();
  },
  _removeCombatant(id){
    const C = panelDefs.combat; if (!C) return;
    const i = this._order().findIndex(c => c.id === id); if (i < 0) return;
    const gone = this._order()[i];
    if (this._armed === id) this._armed = null;
    if (this._pending && ((this._pending.target && this._pending.target.id === id)
                       || (this._pending.mover && this._pending.mover.id === id))) this._pending = null;
    C._removeCombatantAt(i);
    this._log.unshift(`<strong>${esc(gone.name)}</strong> left the fight`);
    save(); C._render?.(); this._render();
  },
  _endTurn(){
    if (this._pending){ showToast('Resolve the reaction first'); return; }
    this._armed = null;
    this._setResult('');
    panelDefs.combat?._nextTurn?.();
    this._render();
  },

  // ─── Interaction ──────────────────────────────────────────────────────────
  _wire(){
    const b = this._body; if (!b || b._tvWired) return;
    b._tvWired = true;

    b.addEventListener('click', e => {
      const el = e.target.closest('[data-tv]'); if (!el) return;
      const act = el.dataset.tv;
      if (act === 'jump'){ state.activeCombatantId = el.dataset.id; this._armed = null; save(); panelDefs.combat?._render?.(); this._render(); }
      else if (act === 'initedit'){ this._editInit = true;  this._render(); }
      else if (act === 'initdone'){ this._editInit = false; this._render(); }
      else if (act === 'rollinit'){ this._rollNpcInit(); }
      else if (act === 'add'){ this._addCombatant(); }
      else if (act === 'rm'){ this._removeCombatant(el.dataset.id); }
      else if (act === 'arm'){ this._armed = el.dataset.id; this._render(); }
      else if (act === 'roll'){ this._rollAttack(+el.dataset.ai); }
      else if (act === 'manual'){ this._manualAttack(); }
      else if (act === 'adj'){ this._adjust(+el.dataset.sign); }
      else if (act === 'end'){ this._endTurn(); }
      else if (act === 'oa'){ if (el.dataset.id) this._useOA(el.dataset.id); else { this._pending = null; this._render(); } }
      else if (act === 'react'){
        const k = el.dataset.key;
        if (k === '__none') this._commit(this._pending, null);
        else this._useReaction(el.dataset.who, k);
      }
    });

    // change, not input — re-sorting on every keystroke would rip the field out
    // from under the cursor halfway through typing "12".
    b.addEventListener('change', e => {
      const f = e.target.closest('[data-tvinit]');
      if (f) this._setInit(f.dataset.tvinit, parseInt(f.value, 10));
    });
    b.addEventListener('keydown', e => {
      if (e.key === 'Enter' && e.target.closest('.tv-init-add')){ e.preventDefault(); this._addCombatant(); }
    });

    // Map: enlarge on approach so it is already the right size by the time the
    // cursor arrives, and stay big while dragging or it would collapse under
    // the pointer mid-drag.
    b.addEventListener('pointerenter', e => {
      if (e.target.closest && e.target.closest('.tv-map') && !this._mapBig){ this._mapBig = true; this._reflowMap(); }
    }, true);
    b.addEventListener('pointerleave', e => {
      if (e.target.closest && e.target.closest('.tv-map') && this._mapBig && !this._drag){ this._mapBig = false; this._reflowMap(); }
    }, true);

    b.addEventListener('pointerdown', e => {
      const t = e.target.closest('.tv-tok'); if (!t) return;
      // Read-only when the battle map hasn't mounted — see _mapSrc.
      if (!this._map().live){ showToast('Open the Battle Map to move tokens'); return; }
      const c = this._order().find(x => x.id === t.dataset.tvtok);
      const tok = this._tokenFor(c); if (!tok) return;
      this._drag = { id: c.id, from: { x: tok.x, y: tok.y } };
      try { t.setPointerCapture(e.pointerId); } catch(err){}
      e.preventDefault();
    });
    b.addEventListener('pointermove', e => {
      if (!this._drag) return;
      const m = b.querySelector('.tv-map'); if (!m) return;
      const c = this._order().find(x => x.id === this._drag.id);
      const tok = this._tokenFor(c); if (!tok) return;
      const src = this._map(), vp = this._viewport(), r = m.getBoundingClientRect();
      const cs = src.cs || 50;
      // Same letterbox the tokens are drawn with, or the drop lands a square
      // off wherever the black bars are.
      const cell = Math.min(r.width / vp.w, r.height / vp.h);
      const offX = (r.width - cell * vp.w) / 2, offY = (r.height - cell * vp.h) / 2;
      const cx = vp.x + Math.floor((e.clientX - r.left - offX) / cell);
      const cy = vp.y + Math.floor((e.clientY - r.top - offY) / cell);
      tok.x = Math.max(0, Math.min(src.cols - 1, cx)) * cs;
      tok.y = Math.max(0, Math.min(src.rows - 1, cy)) * cs;
      this._placeTokens();
    });
    b.addEventListener('pointerup', () => {
      const d = this._drag; if (!d) return;
      this._drag = null;
      const B = this._bm();
      const mover = this._order().find(x => x.id === d.id);
      const tok = this._tokenFor(mover);
      // Write through to the battle map — this IS its token, so the panel and
      // the map can't disagree about where anyone is standing.
      B?._renderTokens?.(); B?._saveMap?.();
      const moved = tok && (tok.x !== d.from.x || tok.y !== d.from.y);
      if (moved && !this._pending){
        const rows = this._provokedBy(mover, d.from);
        if (rows.length){
          const cs = this._cs() || 50;
          const ft = Math.round(Math.max(Math.abs(tok.x - d.from.x), Math.abs(tok.y - d.from.y)) / cs) * 5;
          this._pending = { kind:'move', mover, rows, moved: ft };
        }
      }
      this._render();
    });
  },

  // The enlarge is a class swap, but token offsets are computed from the box's
  // pixel size — so they have to be recomputed once it has the new one.
  _reflowMap(){
    const b = this._body; if (!b) return;
    const m = b.querySelector('.tv-map'); if (!m) return;
    m.classList.toggle('big', this._mapBig);
    const h = m.querySelector('.tv-map-hint');
    if (h) h.textContent = this._mapBig ? 'drag a token — reach updates live, and leaving it provokes'
                                        : (matchMedia('(pointer: coarse)').matches ? 'tap to enlarge' : 'hover to enlarge');
    requestAnimationFrame(() => this._placeTokens());
  },
});
